server:
    port: 9000
    servlet:
        context-path: /roomly-services/api

spring:
    application:
        name: roomly-services
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
#        driver-class-name: org.h2.Driver
#        url: jdbc:h2:mem:testdb
#        username: sa
#        password: sa

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        show-sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
#            ddl-auto: create-drop
            jdbc:
                batch_size: 50
                batch_versioned_data: true
            order_inserts: true
            order_updates: true
            generate_statistics: false
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

upload:
    directory: uploads/images/

cors:
  allowed:
    origins: http://localhost:5173,http://18.205.14.166:8080

cloud:
  aws:
    s3:
      bucket: dh-integration-s3
    region:
      static: us-east-1
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

email:
    host: smtp.gmail.com
    port: 587
    username: jesus.delivery2611@gmail.com
    password: ${EMAIL_PASSWORD}