server:
  port: 9000
  servlet:
    context-path: /roomly-services/api

spring:
  application:
    name: roomly-services
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: ${SPRING_DATASOURCE_URL}
    #    username: ${SPRING_DATASOURCE_USERNAME}
    #    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch_size: 50
        batch_versioned_data: true
      order_inserts: true
      order_updates: true
      generate_statistics: false
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

upload:
  directory: uploads/images/

cors:
  allowed:
    origins: http://localhost,http://107.21.81.113:8080